# Generated by Django 3.1.1 on 2020-10-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('shortcode', models.CharField(max_length=6, unique=True)),
                ('created', models.CharField(max_length=24)),
                ('lastRedirect', models.CharField(max_length=24)),
                ('redirectCount', models.IntegerField(default=0)),
            ],
        ),
    ]
