# Generated by Django 3.1.1 on 2020-10-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
