# Generated by Django 3.1.1 on 2020-10-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_urls', '0002_auto_20201004_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
