# Generated by Django 3.1.1 on 2020-11-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_urls', '0003_auto_20201004_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
